### ISSUE TITLE
Theme 0.1

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#116]
## Overview

This epic is the `frontend` complement of https://github.com/tradingstrategy-ai/design-system/issues/11.

The overall goal of this epic is to implement the [Trading Strategy Design System](https://github.com/tradingstrategy-ai/design-system) Theme 0.1 in the `frontend` web application.

## Breakdown

Each of the sub-sections below represents a scope that can be independently deployed. After _Fonts and colors_, the sequencing of other sub-sections can be re-ordered as needed to align with the order of `design-system` component availability.

### Fonts and colors

- [x] #118
- [x] #119
- [x] ~~Add dark-mode theme based on OS `prefers-color-scheme` value~~

### Navigation / Page chrome

- [x] Header (nav) – desktop
- [x] Header (nav) – mobile (collapsed / hamburger)
- [x] Footer

### Blog Pages

- [x] #144
- [x] #149

### Additional Pages

- [x] #155
- [x] #157
- [x] #162
- [x] #164

**Comment by kenkunz** [comment]
With https://github.com/tradingstrategy-ai/design-system/pull/40 merged, I began the work of integrating the `design-system` repo / components into `frontend`.

I tried integrating the `design-system` color pairings into `frontend` to implement dark mode. Unfortunately, this is very difficult to do with the bootstrap v4 theme. Bootstrap compiles the theme colors from SCSS to CSS, and does not use / support CSS variables in the compilation. The resulting CSS file hard-codes the hex colors into hundreds of CSS selectors. It would be a lot of work (and a messy, fragile hack) to try to override all these occurrences.

Our time will be better spent by implementing the new `design-system` components, and testing the new dark mode as we re-implement each page. Once all pages have been migrated to use the `design-system`, we should be able to enable dark mode.
