### ISSUE TITLE
Remove Bootstrap 4 theme

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#313]
# Goal

Fully remove the old Bootstrap 4 theme from `frontend`.

## Background

See: #231, tradingstrategy-ai/trade-executor-frontend#11

With the above work complete, there is now very little `frontend` code that depends on the Bootstrap theme. Any "straggler" components should be refactored to remove bootstrap dependence. The `deps/theme` submodule can then be dropped.

## Tasks

- [x] upgrade `deps/trade-executor-frontend` to latest (from tradingstrategy-ai/trade-executor-frontend#12)
- [x] remove `deps/theme` submodule
- [x] review and fix any straggler pages / components that still rely on old Bootstrap 4 classes
- [x] review all other pages to ensure that removal of Bootstrap didn't break any CSS
- [x] simplify CSS rules that previously required higher precedence selectors or `!important` to override Bootstrap (see `layout.css`, `reset.css`, typography.css` as well as specific components)
- [x] update scripts and build pipeline to remove anything related to Bootstrap theme
- [x] update docs to remove anything related to Bootstrap theme

### Nice-to-have

With `deps/theme` removed, we still have 2 submodules – `fonts` and `trade-executor-frontend`. We should explore the possibility of removing submodule dependencies entirely:
- `trade-executor-frontend` is now much simpler and could possibly be included as an `npm` module instead
- `fonts` is a private repo and could possibly use the same `optional` approach as `chartiq-dist`
