### ISSUE TITLE
Strategy UI Improvements

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#350]
# Summary

In working on various strategy notebooks, @AlexTheLion123 has identified a number of strategy UI improvements for `frontend`. See [Google spreadsheet](https://docs.google.com/spreadsheets/d/1atg4FQ8Lca2s6WoyT1CZNHwzkIIfgZB1OsFNzY8A-Ao) for additional details (requires org permissions).

## Details

- [x] tradingstrategy-ai/frontend#348
- [x] tradingstrategy-ai/frontend#351
- [x] tradingstrategy-ai/frontend#352
- [x] tradingstrategy-ai/frontend#353
- [x] tradingstrategy-ai/trade-executor-frontend#13
- [x] tradingstrategy-ai/frontend#383
- [ ] tradingstrategy-ai/frontend#354
- [x] tradingstrategy-ai/frontend#355
- [x] tradingstrategy-ai/frontend#356
- [x] tradingstrategy-ai/frontend#357
- [ ] tradingstrategy-ai/frontend#358

## Sources / UI inspiration

- [Enzyme](https://app.enzyme.finance) (we will be integrating with them; long-run we'll have our own smart contracts)
- [DarwinX](https://darwinex.com) - TradFi environment
- [MyFxBook](https://www.myfxbook.com/members/Seventhytheee/seventhythree-sp-zoo/10012365) - Forex (foreign exchange) trading environment
- [Quantstats](https://github.com/ranaroussi/quantstats) - source of stats used by others in this space
