### ISSUE TITLE
🧙‍♂️ Investor Wizards

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#412]
# Goal

Implement **Investor** workflows for connecting wallet, deposit and withdrawal.

## Requirements and UI Design

- see [Investor mini UI](https://docs.google.com/presentation/d/10msg2G_XaW3dozkaWnrrPtwJa1g-WBuzvRc0hNHDGVQ/) wireframes (requires access to Trading Strategy google apps).
- see tradingstrategy-ai/design-system#121 and #409

## UX / UI flows

- [x] tradingstrategy-ai/design-system#121
- [x] Add header/footer
- [x] tradingstrategy-ai/design-system#123
- [x] tradingstrategy-ai/design-system#124

### Strategy Investor widget

- [x] basic investor widget buttons (connect wallet, deposit, redeem)
- [x] #433
- [x] #441
- [x] #447

### Connect Wallet Wizard

- [x] component design / implementation v1
- [x] #413
- [x] #414
- [x] #415
- [x] #416

### Deposit Wizard

- [x] component design / implementation v1
- [x] #418
- [x] #425
- [x] #426
- [x] #455

### Redeem Wizard

- [x] component design / implementation v1
- [x] #450
- [x] #463
- [x] #464

### Other

- [x] #467
- [x] #468
