### ISSUE TITLE
Update lending reserve pages to match API changes

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#465]
# Goal

Pages that show fetch and display lending reserve data should be updated to match the recent `backend` API changes from tradingstrategy-ai/backend#167.

## Details

We currently have two orphaned routes for displaying lending reserves:
- `trading-view/reserves`
- `trading-view/[chain]/lending/[protocol]/[reserve]`

These routes request data from `/api/reserves` and `/api/reserve/details` respectively. These need to be updated to the new API endpoints, and the index route should be updated to `lending-reserves` for consistency.

## Tasks

- [x] move `trading-view/reserves` to `trading-view/lending-reserves`
- [x] update `/api/reserves` API endpoint to `/api/lending-reserves` 
- [x] update `/api/reserve/details` API endpoint to `/api/lending-reserve/details`
- [x] rename other files / components (e.g., `reserve-client.ts` / `ReserveTable.svelte`)
- [ ] remove hard-coded `protocol_slug` (blocked by tradingstrategy-ai/backend#168)
