### ISSUE TITLE
Aave: Audit and optimize lending reserves in search

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#534]
> **Note**
> ~**blocked** by tradingstrategy-ai/search#15, tradingstrategy-ai/oracle#405~

# Goal

As an Investor or Strategy Developer, I want to see lending reserves in search results displayed in an intuitive manner.

## Details

Once lending reserves are added to our search index (see tickets listed above), they should automagically start appearing in search results – both "basic" search (top nav) and advanced search (`/search`).

Audit the search results and optimize the data displayed for lending reserves.

## Tasks

- [x] add a CSS class / color for lending reserve label
- [x] "humanize" facet filter value ("lending_reserve" → "lending reserve")
- [x] add blockchain icon
- [x] check order of result hits
- [x] ~consider including Variable Borrow APR in basic search hit template~
- [x] include various APRs in advanced search hit template
- [x] add interest rate sort options to advanced search

**Comment by kenkunz** [comment]
@miohtama we need a label for "Lending Reserves" in search results (the full label is too long … unless we want to wrap the label to two lines.

> **Note**
> This is a provisional solution until we decide to prioritize tradingstrategy-ai/design-system#133 (finalize and implement the updated search result design)


I tested three alternatives:
1. **Reserves** – need to reduce the label font size and increase the label width
2. **Lending** – requires slightly less space, but still need to reduce the label font size and increase the label width
3. **Aave** – since we only support Aave lending protocol for now (and foreseeable future), we could consider just using "Aave" as label – allows us to retain original font size and label width.

Here are screenshots of the three options. I also tested them with a variable width label instead of fixed. I recall you have indicated a strong preference for fixed width in the past, but the variance in label widths makes the "DEX" and "Pair" labels look a bit strange to me in the fixed-width option (too much horizontal padding). We could potentially mitigate this by using "Exchange" instead of "DEX".

| Label | Fixed width | Variable width |
| --- | --- | --- |
| **Reserve** | ![lending_reserve_search_reserve_fixed](https://github.com/tradingstrategy-ai/frontend/assets/35901/d405322e-7476-4c6c-b6d5-090753bfe173) | ![lending_reserve_search_reserve_var](https://github.com/tradingstrategy-ai/frontend/assets/35901/90294254-1c5a-46dc-b35a-76c7a4559854) |
| **Lending** | ![lending_reserve_search_lending_fixed](https://github.com/tradingstrategy-ai/frontend/assets/35901/9ecfb403-de87-48f0-887e-798905696851) | ![lending_reserve_search_lending_var](https://github.com/tradingstrategy-ai/frontend/assets/35901/5aebbae1-0663-4b2b-82d6-dbd9e96e8f97) |
| **Aave** | ![lending_reserve_search_aave_fixed](https://github.com/tradingstrategy-ai/frontend/assets/35901/4099f19a-d9a6-4a6a-bc19-e396db575ec8) | ![lending_reserve_search_aave_var](https://github.com/tradingstrategy-ai/frontend/assets/35901/52e49a34-04ef-441f-b7cb-575b252fb581) |

**Comment by kenkunz** [comment]
**UPDATE:**

Went with the first option ("Reserve") – it's easy enough to change later.

Here's the final version with the addition of a chain icon:

![localhost_5173_](https://github.com/tradingstrategy-ai/frontend/assets/35901/ba2b263e-7849-41c7-aa86-60f9e3ae20fd)
