### ISSUE TITLE
Merge `trade-executor-frontend` into `frontend`

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#537]
# Goal

Simplify development by merging [`trade-executor-frontend`](https://github.com/tradingstrategy-ai/trade-executor-frontend) repo into [`frontend`](https://github.com/tradingstrategy-ai/frontend)

## Details

Previously, when we were migrating off of the Bootstrap 4 theme, we moved all components from `trade-executor-frontend` into `frontend`. This reduced the footprint of `trade-executor-frontend` to just API adapters, helpers and types.

Based on a [recent discussion](https://discord.com/channels/888448459168948284/1134074252899917834) on Discord, we agreed to fold the remaining pieces into `frontend` as well.

In the future, should we need to expose `trade-executor-frontend` functionality to be imported into a different web frontend, we could potentially use `@sveltejs/package` to export just the relevant files into a separate `npm` module.

## Tasks

- [x] rename alias to `trade-executor`
- [x] copy `config.ts` configuration into `frontend`'s config
- [x] copy all required libs into `frontend:src/lib/trade-executor/`
- [x] update alias to point to new location
- [x] remove `git submodule`
- [x] remove any CI setup related to `trade-executor-frontend`
- [x] remove and/or update any documentation related to `trade-executor-frontend`
- [x] move `position-data` to `lib/trade-executor` subtree
- [x] test docker build before deploying
