### ISSUE TITLE
Trading entity page refresh (part 2)

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#784]
See #636

# Goal

As an investor, I want various trading entity pages (chains, exchanges, tokens, pairs, lending reserves) to be up to date with the most relevant and useful information, so that I can effectively research and analyze trading opportunities.

### Frontend tickets

- [ ] #639 

### Oracle / Backend dependencies

- [ ] tradingstrategy-ai/oracle#474
- [ ] tradingstrategy-ai/backend#226
- [ ] tradingstrategy-ai/backend#225
- [ ] add a back-ref to lending reserve to token details if available for the token (future-proof – could be multiple lending reserves for a given token, across different lending protocols)
- [ ] add highest/lowest TVL values to `pair-trade-data` endpoint (to replace `liquidity`)
