### ISSUE TITLE
Velvet Capital vault integration

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#865]
# Goal

The goal of this epic is to add support to our UI for [Velvet Capital](https://www.velvet.capital/) vaults. At a high level, strategies that use a Velvet-Capital-based vault should support the same information and operations in our UI as current strategies using Enzyme-based vaults (though some details or flow of operations may differ).

## Tickets

- [ ] Velvet Capital: "asset management" info on the strategy tile
- [ ] Velvet Capital: into and links on the strategy `/vault` page
- [ ] Velvet Capital: fee information on the strategy `/fees` page
- [ ] Velvet Capital: strategy deposit flow
- [ ] Velvet Capital: strategy redemption (withdrawal) flow
